\doxysection{Known\+Failure\+Exception Class Reference}
\hypertarget{classnumpy_1_1testing_1_1__private_1_1utils_1_1_known_failure_exception}{}\label{classnumpy_1_1testing_1_1__private_1_1utils_1_1_known_failure_exception}\index{KnownFailureException@{KnownFailureException}}
Inheritance diagram for Known\+Failure\+Exception\+:\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[height=2.000000cm]{classnumpy_1_1testing_1_1__private_1_1utils_1_1_known_failure_exception}
\end{center}
\end{figure}


\doxysubsection{Detailed Description}
\begin{DoxyVerb}Raise this exception to mark a test as a known failing test.\end{DoxyVerb}
 

The documentation for this class was generated from the following file\+:\begin{DoxyCompactItemize}
\item 
fluent20.\+1.\+0/cortex/pylib/nexus/numpy/testing/\+\_\+private/\mbox{\hyperlink{testing_2__private_2utils_8py}{utils.\+py}}\end{DoxyCompactItemize}
